<?php

function datapoint_yahooweather_datapoint() {
  return array(
    'update_limit' => 60*60*3, //Three hours
  );
}

function datapoint_yahooweather_datapoint_source_configure($configuration) {
  $settings = array();
  $settings['city_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Yahoo city code'),
    '#default_value' => $configuration['city_code'],
  );
  return $form;
}

function datapoint_yahooweather_datapoint_source_configure_submit($form, $state) {
  var_dump($form, $state); die;
}

function datapoint_yahooweather_datapoint_parseresult($data, &$results) {
  $doc = new DOMDocument();
  $doc->loadXML($data);
  $items = $doc->getElementsByTagNameNS('http://xml.weather.yahoo.com/ns/rss/1.0', 'forecast');
  foreach ($items as $item) {
    print '<p>';
    foreach ($item->attributes as $attr => $attrNode) {
      $value = $attrNode->value;
      if ($attr == 'date') {
        $value = date('c', strtotime($value));
      }
      print $attr . ' = ' . $value . '<br/>';
    }
    print '</p>';
  }
}