<?php
// $Id$

if (!defined('NS_YAHOO_WEATHER')) {
  define('NS_YAHOO_WEATHER', 'http://xml.weather.yahoo.com/ns/rss/1.0');
}
if (!defined('YAHOO_WEATHER_ENDPOINT')) {
  define('YAHOO_WEATHER_ENDPOINT', 'http://xml.weather.yahoo.com/forecastrss');
}

function datapoint_yahooweather_datapoint_parser() {
  return array(
    'name' => t('Yahoo Weather'),
    'configuration' => '_datapoint_yahooweather_configuration',
    'update limit' => 60*60*3, //Three hours
    'source configuration'        => '_datapoint_yahooweather_configuration',
    'source configuration submit' => '_datapoint_yahooweather_configuration_submit',
    'fetch'                       => '_datapoint_yahooweather_fetch',
  );
}

function _datapoint_yahooweather_configuration($configuration) {
  $settings = array();
  $settings['city_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Yahoo city code'),
    '#default_value' => $configuration['city_code'],
  );
  return $settings;
}

function _datapoint_yahooweather_configuration_submit($values) {
  return array(
    'city code' => $values['city_code'],
  );
}

function _datapoint_yahooweather_fetch($source, &$result) {
  $city = $source['source configuration']['city code'];
  datapoint_url_fetch(YAHOO_WEATHER_ENDPOINT . '?p=' . $city . '&u=c',
    $source, $result, '_datapoint_yahooweather_datapoint_parseresult');
}

function _datapoint_yahooweather_datapoint_parseresult($data, &$source, &$result) {
  $doc = new DOMDocument();
  $doc->loadXML($data);

  $point = $point = $result->point($source['source configuration']['city code']);
  $point->setName($source['source configuration']['city code']);
  $point->setHasNodes(FALSE);

  $items = $doc->getElementsByTagNameNS(NS_YAHOO_WEATHER, 'forecast');
  foreach ($items as $item) {
    $time = strtotime($item->getAttribute('date'));
    $vertex = new DatapointVertex($time);
    $vertex->xmlAttributes($item, array(
      'low'  => 'low',
      'high' => 'high',
      'text' => 'text',
      'code' => 'code',
    ));
    $point->addVertex($vertex);
  }
}

/**
 * Implementation of hook_views_handlers() to register all of the basic handlers
 * views uses.
 */
function datapoint_yahooweather_views_handlers() {
  return array(
    'info' => array(
      'path' => drupal_get_path('module', 'datapoint') . '/includes',
    ),
    'handlers' => array(
      'views_handler_field_yahoo_weather_code' => array(
        'parent' => 'views_handler_field',
      ),
      'views_handler_field_yahoo_weather_temperature' => array(
        'parent' => 'views_handler_field',
      )
    ),
  );
}