<?php
// $Id$

function datapoint_simple_geo_datapoint_managed_fields_alter(&$fields, $type) {
  $has_position = variable_get('allow_position_'. $type->type, FALSE);

  if ($has_position) {
    $fields['simple_geo_position'] = array(
      'label' => t('Position'),
      'required' => FALSE,
      'setter' => '_datapoint_simple_geo_set_position',
    );
  }
}

function _datapoint_simple_geo_set_position(&$node, $field, $setter, $value) {
  $node->simple_geo_position = $value;
}